on:
  merge_group:
  pull_request:

name: CI

permissions:
  contents: read

jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: "nocommit checker"
        uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3

  nix-flake-check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          #  FIXME: Mac building the typescript apps is not working on CI.
          #  Issues with building node-modules.  Also it doesn't like enable_kvm
          #  or the extra_nix_config.
          # - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
        with:
          enable_kvm: true
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - run: nix run .#nix-flake-check-changed

  nix-flake-health:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
      - run: nix flake show
      - run: nix flake lock --no-update-lock-file
      - run: nix flake check --no-build
