on:
  push:

name: CI
jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - name: "nocommit checker"
        uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3
