on:
  push:

name: CI
jobs:
  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: "nocommit checker"
        uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3
