on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

name: PR

jobs:
  conventional-commit:
    name: "PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
      - run: |
          <<<"$TITLE" nix run .#conventional-commit
        env:
          TITLE: "${{ github.event.pull_request.title || github.event.merge_group.head_commit.message }}"

  merging-into-master:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: |
          [[ "$GITHUB_BASE_REF" == master ]]
