on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  merge_group:

name: PR

jobs:
  conventional-commit:
    name: "PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          key: "nix-eval-cache-${{ runner.os }}-${{ runner.arch }}"
          path: "~/.cache/nix"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c
      - run: |
          <<<"$TITLE" nix run .#conventional-commit
        env:
          TITLE: "${{ github.event.pull_request.title || github.event.merge_group.head_commit.message }}"

  merging-into-master:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: |
          [[ "$GITHUB_BASE_REF" == master ]]
